# Generated by Django 5.1.6 on 2025-02-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("contact_email", models.EmailField(max_length=254)),
                (
                    "standard_crayon_price",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "premium_crayon_price",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "eco_friendly_crayon_price",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("offers_bulk_discount", models.BooleanField(default=False)),
            ],
        ),
    ]
